name: GitHub Actions
run-name: ${{ github.actor }} GitHub Actions ðŸš€
on:
  push:
    branches:
      - main
    paths:
      - 'pipa-dev/**' # Trigger only if changes are in the 'pipa-dev' directory or its subdirectories

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Optional: Caches node_modules for faster subsequent runs

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI environments

      - name: Build project
        run: npm run build

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Optional: Verify AWS credentials (uncomment if needed)
      # - name: Verify AWS Credentials
      #   run: aws sts get-caller-identity

      - name: Push S3 bucket and invalidate CloudFront cache
        run: |
          aws s3 sync ./dist s3://pipa-web-dev --delete
          aws cloudfront create-invalidation \
            --distribution-id E37CWSMXISOVCA \
            --paths "/*"